services:
  backend:
    image: ghcr.io/lorisforse/zipply-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ziply-backend
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=ziply-postgres
      - DB_PORT=5432
      - DB_NAME=ziply_db
      - DB_USER=ziply
      - DB_PASSWORD=ziply_password
      - JWT_SECRET=ziply_jwt_secret_dev
      - SERVER_PORT=8080
    networks:
      - ziply-net

networks:
  ziply-net:
    external: true